Repository studtool/frontend, pull requests merged in 2019-05, with the labels that each got.

#16 15 atomic
  src/app/components/atoms/button/__snapshots__/button.test.js.snap
  src/app/components/atoms/button/button.js
  src/app/components/atoms/button/button.test.js
  src/app/components/atoms/inputTextField/__snapshots__/inputTextField.test.js.snap
  src/app/components/atoms/inputTextField/inputTextField.js
  src/app/components/atoms/inputTextField/inputTextField.test.js
  src/app/components/container/container.js
  src/app/components/container/container.scss
  src/app/components/container/content/content.js
  src/app/components/container/content/content.scss
  src/app/components/container/content/main/main.js
  src/app/components/container/content/main/main.scss
  src/app/components/container/content/signUp/signUp.js
  src/app/components/container/head/head.js
  src/app/components/molecules/inputText/__snapshots__/inputText.test.js.snap
  src/app/components/molecules/inputText/inputText.js
  src/app/components/molecules/inputText/inputText.test.js
  src/app/components/organisms/header/__snapshots__/header.test.js.snap
  src/app/components/organisms/header/header.js
  src/app/components/organisms/header/header.test.js
  src/app/components/organisms/signUpForm/__snapshots__/signUpForm.test.js.snap
  src/app/components/organisms/signUpForm/signUpForm.js
  src/app/components/organisms/signUpForm/signUpForm.test.js
  src/app/pages/main/main.js
  src/app/pages/signUp/signUp.js
  src/app/pages/signUp/singUpController.js
  src/modules/controller.js
  src/script.js
Labels: enhancement

#13 signup signin models added
  .eslintrc.json
  package-lock.json
  package.json
  src/app/Errors/inputValidationErrors.js
  src/app/actionCreator/actionCreator.js
  src/app/actionCreator/actionFormatMethods.js
  src/app/actionCreator/actionTypes.js
  src/app/actionCreator/actionTypesBody.js
  src/app/actionCreator/coreMessageTypes.js
  src/app/components/atoms/button/button.js
  src/app/components/atoms/button/button.test.js
  src/app/components/atoms/inputTextField/inputTextField.js
  src/app/components/atoms/inputTextField/inputTextField.test.js
  src/app/components/atoms/label/label.test.js
  src/app/components/atoms/style.js
  src/app/components/molecules/inputText/inputText.js
  src/app/components/molecules/inputText/inputText.test.js
  src/app/components/organisms/header/header.js
  src/app/components/organisms/header/header.test.js
  src/app/components/organisms/signUpForm/signUpForm.js
  src/app/components/organisms/signUpForm/signUpForm.test.js
  src/app/dispatcher/dispatcher.js
  src/app/models/authModel.js
  src/app/pages/main/main.js
  src/app/pages/signUp/signUp.js
  src/app/pages/signUp/singUpController.js
  src/app/store/formStores/signUpFormStore/signUpFormLogic.js
  src/app/store/formStores/signUpFormStore/signUpFormStore.js
  src/app/store/formStores/signUpStore/signUpLogic.js
  src/app/store/formStores/signUpStore/signUpStore.js
  src/app/store/store.js
  src/app/validators/signUpValidator.js
  src/models/authModel.js
  src/modules/Bus.js
  src/modules/Router.js
  src/modules/ajax.js
  src/modules/controller.js
  src/modules/fetchModule.js
  src/modules/postman.js
  src/modules/protocol.js
  src/modules/utils.js
  webpack.config.js
Labels: enhancement

#14 Script to build image update. Now with "run" command
  image.sh
Labels: dev

#17 image.sh update
  image.sh
Labels: dev

#19 Dev
  .babelrc
  .eslintrc.json
  .gitignore
  .travis.yml
  Dockerfile
  image.sh
  nginx.conf
  package-lock.json
  package.json
  server/index.js
  serviceScript.js
  src/app/Errors/inputValidationErrors.js
  src/app/actionCreator/actionCreator.js
  src/app/actionCreator/actionFormatMethods.js
  src/app/actionCreator/actionTypes.js
  src/app/actionCreator/actionTypesBody.js
  src/app/actionCreator/coreMessageTypes.js
  src/app/components/atoms/button/__snapshots__/button.test.js.snap
  src/app/components/atoms/button/button.js
  src/app/components/atoms/button/button.test.js
  src/app/components/atoms/inputTextField/__snapshots__/inputTextField.test.js.snap
  src/app/components/atoms/inputTextField/inputTextField.js
  src/app/components/atoms/inputTextField/inputTextField.test.js
  src/app/components/atoms/label/__snapshots__/label.test.js.snap
  src/app/components/atoms/label/label.js
  src/app/components/atoms/label/label.test.js
  src/app/components/atoms/style.js
  src/app/components/molecules/inputText/__snapshots__/inputText.test.js.snap
  src/app/components/molecules/inputText/inputText.js
  src/app/components/molecules/inputText/inputText.test.js
  src/app/components/organisms/header/__snapshots__/header.test.js.snap
  src/app/components/organisms/header/header.js
  src/app/components/organisms/header/header.test.js
  src/app/components/organisms/signUpForm/__snapshots__/signUpForm.test.js.snap
  src/app/components/organisms/signUpForm/signUpForm.js
  src/app/components/organisms/signUpForm/signUpForm.test.js
  src/app/dispatcher/dispatcher.js
  src/app/pages/main/main.js
  src/app/pages/signUp/signUp.js
  src/app/pages/signUp/singUpController.js
  src/app/store/formStores/signUpFormStore/signUpFormLogic.js
  src/app/store/formStores/signUpFormStore/signUpFormStore.js
  src/app/store/store.js
  src/app/validators/signUpValidator.js
  src/index.html
  src/models/authModel.js
  src/modules/controller.js
  src/modules/fetchModule.js
  src/modules/postman.js
  src/modules/protocol.js
  src/script.js
  webpack.config.js
Labels: dev, enhancement
